### ISSUE TITLE
Add dist files to public CDN

### ISSUE THREAD

**Issue by alexgorbatchev** [square/field-kit#16]

**Comment by iamJoeTaylor** [comment]
I'm in contact with https://www.maxcdn.com/open-source/ about the possibility of them hosting FieldKit.

**Comment by iamJoeTaylor** [comment]
Trying CDNJS now, https://github.com/cdnjs/cdnjs/pull/6042

**Comment by iamJoeTaylor** [comment]
Done. https://cdnjs.com/libraries/field-kit
