### ISSUE TITLE
None works in Chrome on Android

### ISSUE THREAD

**Issue by SleeplessByte** [square/field-kit#32]
*Phone number*
Input `4151234567`
Output `(451) 345-672`

*Credit Card*
Input `3725123456`
Output `5123 4563 72`

*Number*
Doesn't do anything

Newest Chrome on Android

**Comment by eventualbuddha** [comment]
Hmm, can you give us some more details about your setup? Perhaps the version of Android, the version of Chrome, and what page you're trying it on? Do you experience the same behavior when going to https://square.github.io/field-kit/?

cc @iamJoeTaylor / @TRMW

**Comment by iamJoeTaylor** [comment]
And device running Android please.

**Comment by TRMW** [comment]
He responded to me on Twitter regarding his setup [here](https://twitter.com/SleeplessByte/status/642423440956346368):

> Android 5.1 latest Chrome. Check the github issue. No keyboard extensions etc. Etc.

**Comment by SleeplessByte** [comment]
Chrome 45.0.24.5484
OnePlus One on Cyanogen 12.1-YOG4PAS1N0
Android 5.1.1

@eventualbuddha that's the page.

Basically the first there characters enter fine, and as I enter the fourth character it inserts it before the first three. And subsequent character works.

**Comment by nahtnam** [comment]
Can confirm the same issue with the credit card form on my OnePlus One. Specs: http://i.imgur.com/UbySSgB.jpg

Haven't tried the other forms.

**Comment by iamJoeTaylor** [comment]
@SleeplessByte and @nahtnam Thanks for reporting this. I'd love to be able to "recreate" the failing keyboard in our tests. We do that for an issue we had with a Samsung device [here](https://github.com/square/field-kit/blob/master/test/unit/helpers/setup.js#L51). The easiest way for me to do this is to see get my hands on the failing phone. We might be able to use this page http://unixpapa.com/js/testkey.html and get us the information.

We might want to treat you @SleeplessByte to lunch, I heard you are in the area.

Once we can reproduce the keyboard we should have failing tests, and can fix from there.

**Comment by SleeplessByte** [comment]
I can drop my phone off anywhere next week except monday!

**Comment by iamJoeTaylor** [comment]
@SleeplessByte @eventualbuddha Lunch on Wed?

**Comment by SleeplessByte** [comment]
Good with me

**Comment by eventualbuddha** [comment]
Sounds good to me.
