### ISSUE TITLE
Currency formats

### ISSUE THREAD

**Issue by mhinton** [square/field-kit#34]
Currency doesn't seem to handle thousands or going out beyond 2 decimal places.

1200 is displayed as 1200 instead of 1,200

1.23434234 is displayed as 1.23434234

**Comment by eventualbuddha** [comment]
@mhinton can you please give a reproducible example, for instance something on jsbin.com?

**Comment by mhinton** [comment]
Sorry, it looks like this isn't a bug it just didn't work quite how I expected.

**Comment by eventualbuddha** [comment]
@mhinton if you have a quick second to explain how you thought it should behave it might help us to update the documentation.
