### ISSUE TITLE
compatibility with react

### ISSUE THREAD

**Issue by fabriziomoscon** [square/field-kit#38]
Hi guys,
great job with the library!

I was wondering if you are aware of any reason why this library wouldn't work 100% with react?
I succeeded using `new FieldKit.CardTextField`, but for some reason I am not having any luck with `new FieldKit.CardTextField` and `new FieldKit.NumberFormatter`, the field value simply doesn't reformat.

I can see people are posting code snippet specific for react interoperability
https://gist.github.com/pascallouisperez/605295fcf21db6175c12

which makes me think for some reason it could not work how of the box.

in case you confirm there are no issues I will extract a code snippet to complete the issue

**Comment by eventualbuddha** [comment]
@fabriziomoscon It sounds like you're trying to use `CardTextField` with `NumberFormatter` as its formatter. If so, that's not supported. Please try `NumberFormatter` with `new FieldKit.TextField` and we'll reopen if you're having trouble.

**Comment by fabriziomoscon** [comment]
Hi @eventualbuddha ,

sorry my copy and paste mistake.

I am using `new FieldKit.TextField`with `new FieldKit.NumberFormatter`

I will try to extract a self contained example with react to see if in isolation I still have problems
