### ISSUE TITLE
Firefox issue - event not defined

### ISSUE THREAD

**Issue by arkoe** [square/field-kit#43]
When using this code:

    field.setFormatter({
	  format: function(value){
	  	var val = $val;
	  	if ( event.charCode >= 48 && event.charCode <= 57) {
	  		val = value;
	  	}

I get an JS error in Firefox that `event` is not defined. How can I define this by default?

**Comment by eventualbuddha** [comment]
I think there's some context that's missing here. What is `$val`? What are you trying to do? If you're trying to restrict entry to digits, try looking at [`SocialSecurityNumberFormatter#isChangeValid`](https://github.com/square/field-kit/blob/master/src/social_security_number_formatter.js#L34-L40).

**Comment by arkoe** [comment]
$val is a value that is defined somewhere else. But it is irrelevant here. The thing is, it seems like firefox doesn't have a global `event`, and it is not passed in the function like in jQuery (`$(obj).click(function(event) { // code });`).

**Comment by eventualbuddha** [comment]
`TextField` is a wrapper that handles the events itself. Formatters are simply that: they provide parsing (`parse`), formatting (`format`), and partial input validation (`isChangeValid`). The DOM events for keypresses are not exposed to your code, but you should nevertheless be able to do whatever you're trying to achieve. Did you look at the example I pointed out?

**Comment by arkoe** [comment]
Yes - I have took a look at the example you gave. However, it is hard for me to understand the existing formatters, and how to modify them. This example is for phone number validation, where I only want 10 digits, no spaces, dashes, or what so on. So I have basically created something myself, checking on keyCodes to ignore other characters.

The PhoneFormatter that exists in the project, doesnt fit my needs, and I don't know how to edit the formatter to my format. Also I think that wouldn't be the best way to do it.

**Comment by eventualbuddha** [comment]
If you're trying to prevent input then you want to implement `isChangeValid`. Please see the [wiki page on formatters](https://github.com/square/field-kit/wiki/Formatters). Here's an example for a simple formatter that lets you enter only digits and only 10 at most: http://jsbin.com/zijuforofi/edit?js,output

```js
new FieldKit.TextField(document.getElementById('phone'), {
  isChangeValid: function(change) {
    if (change.proposed.text.length > 10) {
      // Don't allow more than 10 characters.
      return false;
    }
    // Only allow inserting digits.
    return /^\d*$/.test(change.inserted.text);
  }
});
```

**Comment by arkoe** [comment]
Works like a charm!

Is there any way I can bind these to your code?

    field.setFocusedPlaceholder('0612345678');
    field.setUnfocusedPlaceholder('Telefoonnummer');

Also - is there an easy way to create a custom format, for example: DD-DD-DDDD (date of birth, only digits with dashes).

**Comment by eventualbuddha** [comment]
> Is there any way I can bind these to your code?

Yes, store the result of `new FieldKit.TextField(…)` in a variable then call the methods on them as usual:

```js
var field = new FieldKit.TextField(…);
field.setFocusedPlaceholder('0612345678');
field.setUnfocusedPlaceholder('Telefoonnummer');
```

> Also - is there an easy way to create a custom format, for example: DD-DD-DDDD (date of birth, only digits with dashes).

That is pretty much exactly what the [`SocialSecurityNumberFormatter`](https://github.com/square/field-kit/blob/master/src/social_security_number_formatter.js) does. You'll just need to create your own subclass of `DelimitedTextFormatter` and edit `hasDelimiterAtIndex` to say where the dashes should fall (i.e. at `3` and `5`) and the `constructor` to make a maximum length of `8 + 2` for eight digits and two dashes.

If you're having trouble with the ES6 syntax (`class`) and don't know how to write a subclass in normal JavaScript, I suggest [reading up on the object model in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model) and searching the internet for ["javascript subclassing examples"](https://www.google.com/search?q=javascript+subclassing+examples&oq=javascript+subclassing+examples) for information on how to subclass properly.
