### ISSUE TITLE
Phone number not formatted correctly when deleting

### ISSUE THREAD

**Issue by zzh8829** [square/field-kit#53]
fill in 1 (888) 888 8888

bug 1:
move cursor to right behind 1 
press delete, it become (188) 888 8888 

bug 2
move cursor to right before 8
press delete, it become 8 (888) 888 888

I think this problem happened during format switching, some weird stuff is happening with cursor position and delimiters.

**Comment by iamJoeTaylor** [comment]
@zzh8829  thanks for reporting I've been on vacation. I'll check this out and get a fix out for you.
